### ISSUE TITLE
atmosphere says jqueryui-sortable does not exist

### ISSUE THREAD

**Issue by deanwenick** [rgm/meteor-jquery-ui-sortable#1]
Hi Ryan - 

Thanks for packaging up jqueryui-sortable for meteor. There is a problem with installing it, though. Maybe because of Meteor .7 upgrade? The error I get is below. similar error with mrt install...

Mac:stories dean$ mrt add jqueryui-sortable

/usr/local/lib/node_modules/meteorite/lib/project.js:225
          throw("Package named " + pkgName + " doesn't exist in your meteor in
                                           ^
Package named jqueryui-sortable doesn't exist in your meteor installation, smart.json, or on atmosphere

**Comment by rgm** [comment]
Hm, have you tried

```
mrt add jquery-ui-sortable
```

You might have missed a hyphen in the name.

**Comment by rgm** [comment]
Ah, and by "you might have missed," I mean _I_ did, with a typo in the README. Whoops. Fixed this in 5b9139e9c70e ... let me know if this works for you now.

**Comment by deanwenick** [comment]
That was it Ryan - Thanks!

I only had one hyphen.

It looked like your package requires jquery 1.10 and Meteor is giving me
1.8. I'll try to figure that out later. In the meantime thanks!

**Comment by rgm** [comment]
Cheers. Let me know if there's any straightforward way to up to jQuery 1.10 or if it's better to drop this package to rely on 1.8 ... I haven't had trouble, but I'm a Meteor newb and someone else on our team may have fixed this issue without my knowledge.

**Comment by deanwenick** [comment]
Thanks for taking care of that. I ended up needing a little more ui functionality so added the whole jquery ui.

I appreciate your help. My app is at photo-story.meteor.com
