### ISSUE TITLE
Change the way to add the package to meteor

### ISSUE THREAD

**Issue by 4lexsky** [rgm/meteor-jquery-ui-sortable#3]
With the new meteor package manager, the command to add the package should be 

```
meteor add mrt:jquery-ui-sortable
```

**Comment by dandv** [comment]
You may want to check out the official integration from @rubaxa's Sortable, which doesn't depend on jQuery and uses the native HTML5 drag'n'drop API.

https://atmospherejs.com/rubaxa/sortable

**Comment by rgm** [comment]
@4lexsky Thanks for raising it as an issue... we're not actually using this anymore so:
1. I'll likely never get around to this, and 
2. I'll see about getting the package removed from Atmosphere.

**Comment by dandv** [comment]
Thanks @rgm. Atmosphere can't remove packages yet, but you can hide them from searches:

```
meteor admin set-unmigrated <package:name>
```

**Comment by rgm** [comment]
@dandv thanks for the hint. This is done.
